### ISSUE TITLE
Login_Datenfluss

### ISSUE THREAD

**Issue by lsxyz** [NoctivagusObitus/EinkaufsApp-Design#1]
![datenfluss_login](https://cloud.githubusercontent.com/assets/15016730/10507317/e6490e7a-731f-11e5-812d-4a5b281e2b2f.png)

**Comment by lsxyz** [comment]
Wird auch Konsistenz Probleme haben, aber als eine schnelle grafische Darstellung des .txt's

**Comment by NoctivagusObitus** [comment]
lass mich in ruhe
